export const FetchGanttTasksActionTypes = {
    FETCH_GANTT_TASKS_REQUEST: 'FETCH_GANTT_TASKS_REQUEST',
    FETCH_GANTT_TASKS_SUCCESS: 'FETCH_GANTT_TASKS_SUCCESS',
    FETCH_GANTT_TASKS_FAILURE: 'FETCH_GANTT_TASKS_FAILURE',
};